version: "3.7"

services:
  specification:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:13"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: spec_db
      POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM