version: '3'

services:
  postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=spec_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  specification:
    depends_on:
      - postgres
    image: "specification-specification"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/spec_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
volumes:
  postgres-data: